/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Schefer
 */
public class FormAsientos extends javax.swing.JFrame {

    /**
     * Creates new form FormAsientos
     */
    public FormAsientos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDebeHaber = new javax.swing.ButtonGroup();
        grupoTipoAsiento = new javax.swing.ButtonGroup();
        panelPrincipal = new javax.swing.JPanel();
        etiquetaTitulo = new javax.swing.JLabel();
        botonRetomarAsiento = new javax.swing.JButton();
        botonListar = new javax.swing.JButton();
        botonNuevoAsiento = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        campoDesde = new javax.swing.JTextField();
        etiquetaDesde = new javax.swing.JLabel();
        etiquetaHasta = new javax.swing.JLabel();
        campoHasta = new javax.swing.JTextField();
        etiquetaListar = new javax.swing.JLabel();
        panelAsientos = new javax.swing.JPanel();
        fechaContable = new com.toedter.calendar.JDateChooser();
        etiquetaFechaContable = new javax.swing.JLabel();
        etiquetaNroAsiento = new javax.swing.JLabel();
        campoAsiento = new javax.swing.JTextField();
        checkInflacion = new javax.swing.JCheckBox();
        botonIniciarCarga = new javax.swing.JButton();
        botonVolverAtras = new javax.swing.JButton();
        panelRenglones = new javax.swing.JPanel();
        etiquetaNroRenglon = new javax.swing.JLabel();
        campoNroRenglon = new javax.swing.JTextField();
        etiquetaNroCuenta = new javax.swing.JLabel();
        campoNroCuenta = new javax.swing.JTextField();
        etiquetaFechaVencimiento = new javax.swing.JLabel();
        fechaVencimiento = new com.toedter.calendar.JDateChooser();
        fechaOperacion = new com.toedter.calendar.JDateChooser();
        etiquetaFechaOperacion = new javax.swing.JLabel();
        etiquetaSucursal = new javax.swing.JLabel();
        campoSucursal = new javax.swing.JTextField();
        etiquetaSeccion = new javax.swing.JLabel();
        campoSeccion = new javax.swing.JTextField();
        etiquetaComprobante = new javax.swing.JLabel();
        campoComprobante = new javax.swing.JTextField();
        opcionDebe = new javax.swing.JRadioButton();
        opcionHaber = new javax.swing.JRadioButton();
        etiquetaImporte = new javax.swing.JLabel();
        campoImporte = new javax.swing.JTextField();
        etiquetaNombreCuenta = new javax.swing.JLabel();
        campoNombreCuenta = new javax.swing.JTextField();
        campoLeyenda = new javax.swing.JTextField();
        etiquetaLeyenda = new javax.swing.JLabel();
        botonOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRenglones = new javax.swing.JTable();
        botonModificarRenglon = new javax.swing.JButton();
        botonEliminarRenglon = new javax.swing.JButton();
        etiquetaTotalDebe = new javax.swing.JLabel();
        campoTotalDebe = new javax.swing.JTextField();
        etiquetaTotalHaber = new javax.swing.JLabel();
        campoTotalHaber = new javax.swing.JTextField();
        etiquetaDiferencia = new javax.swing.JLabel();
        campoDiferencia = new javax.swing.JTextField();
        botonGrabar = new javax.swing.JButton();
        botonVolverAlInicio = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        etiquetaIDAsiento = new javax.swing.JLabel();
        campoRetomarAsiento = new javax.swing.JTextField();
        panelTipoAsiento = new javax.swing.JPanel();
        etiquetaTipoAsiento = new javax.swing.JLabel();
        opcionApertura = new javax.swing.JRadioButton();
        opcionNormal = new javax.swing.JRadioButton();
        opcionCierre = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        botonSalir = new javax.swing.JButton();
        botonConfirmarAsiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaTitulo.setText("Carga de Asientos");

        botonRetomarAsiento.setText("Retomar Asiento");

        botonListar.setText("Listar");

        botonNuevoAsiento.setText("Nuevo Asiento");

        etiquetaDesde.setText("Desde:");

        etiquetaHasta.setText("Hasta:");

        etiquetaListar.setText("Listar x Nro de Asiento");

        etiquetaFechaContable.setText("Fecha Contable");

        etiquetaNroAsiento.setText("Nro de Asiento");

        campoAsiento.setEnabled(false);

        checkInflacion.setText("Ajustable por Inflación");

        botonIniciarCarga.setText("Iniciar Carga");

        botonVolverAtras.setText("Volver Atras");

        javax.swing.GroupLayout panelAsientosLayout = new javax.swing.GroupLayout(panelAsientos);
        panelAsientos.setLayout(panelAsientosLayout);
        panelAsientosLayout.setHorizontalGroup(
            panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsientosLayout.createSequentialGroup()
                .addGroup(panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAsientosLayout.createSequentialGroup()
                        .addGroup(panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAsientosLayout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(etiquetaNroAsiento))
                            .addGroup(panelAsientosLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(checkInflacion))
                            .addGroup(panelAsientosLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(botonVolverAtras)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonIniciarCarga))
                    .addGroup(panelAsientosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaFechaContable)
                            .addComponent(fechaContable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(campoAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAsientosLayout.setVerticalGroup(
            panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsientosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaFechaContable)
                    .addComponent(etiquetaNroAsiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaContable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAsientosLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(checkInflacion)))
                .addGap(18, 18, 18)
                .addGroup(panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVolverAtras)
                    .addComponent(botonIniciarCarga))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        etiquetaNroRenglon.setText("Nro de Renglon");

        campoNroRenglon.setEnabled(false);

        etiquetaNroCuenta.setText("Nro de Cuenta");

        etiquetaFechaVencimiento.setText("Fecha Vencimiento");

        etiquetaFechaOperacion.setText("Fecha de Operacion");

        etiquetaSucursal.setText("Sucursal");

        etiquetaSeccion.setText("Sección");

        etiquetaComprobante.setText("Comprobante:");

        grupoDebeHaber.add(opcionDebe);
        opcionDebe.setSelected(true);
        opcionDebe.setText("Debe");

        grupoDebeHaber.add(opcionHaber);
        opcionHaber.setText("Haber");

        etiquetaImporte.setText("Importe");

        etiquetaNombreCuenta.setText("Nombre de la Cuenta:");

        campoNombreCuenta.setEnabled(false);

        etiquetaLeyenda.setText("Leyenda:");

        botonOK.setText("Ok");

        tablaRenglones = new javax.swing.JTable() {
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tablaRenglones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nro Renglon", "Nro Cuenta", "Nombre Cta", "Comprobante", "D/H", "Debe", "Haber"
            }
        ));
        jScrollPane1.setViewportView(tablaRenglones);

        botonModificarRenglon.setText("Modificar Renglon");

        botonEliminarRenglon.setText("Eliminar Renglon");

        etiquetaTotalDebe.setText("Total Debe");

        etiquetaTotalHaber.setText("Total Haber");

        etiquetaDiferencia.setText("Diferencia");

        botonGrabar.setText("Grabar");

        botonVolverAlInicio.setText("Volver al Inicio");

        botonCancelar.setText("Cancelar");
        botonCancelar.setEnabled(false);

        javax.swing.GroupLayout panelRenglonesLayout = new javax.swing.GroupLayout(panelRenglones);
        panelRenglones.setLayout(panelRenglonesLayout);
        panelRenglonesLayout.setHorizontalGroup(
            panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRenglonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelRenglonesLayout.createSequentialGroup()
                        .addGroup(panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRenglonesLayout.createSequentialGroup()
                                .addGroup(panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaComprobante)
                                    .addComponent(campoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opcionDebe, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(opcionHaber))
                                .addGap(34, 34, 34)
                                .addGroup(panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaImporte)
                                    .addComponent(campoImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRenglonesLayout.createSequentialGroup()
                                .addComponent(campoNroRenglon, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoNroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRenglonesLayout.createSequentialGroup()
                                .addGroup(panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelRenglonesLayout.createSequentialGroup()
                                        .addComponent(etiquetaFechaOperacion)
                                        .addGap(18, 18, 18)
                                        .addComponent(etiquetaSucursal)
                                        .addGap(18, 18, 18)
                                        .addComponent(etiquetaSeccion))
                                    .addGroup(panelRenglonesLayout.createSequentialGroup()
                                        .addComponent(fechaOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(campoSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(campoSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonModificarRenglon))
                            .addGroup(panelRenglonesLayout.createSequentialGroup()
                                .addGroup(panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etiquetaNombreCuenta))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addComponent(botonEliminarRenglon, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelRenglonesLayout.createSequentialGroup()
                        .addGroup(panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRenglonesLayout.createSequentialGroup()
                                .addComponent(etiquetaNroRenglon)
                                .addGap(18, 18, 18)
                                .addComponent(etiquetaNroCuenta)
                                .addGap(18, 18, 18)
                                .addComponent(etiquetaFechaVencimiento))
                            .addComponent(etiquetaLeyenda)
                            .addGroup(panelRenglonesLayout.createSequentialGroup()
                                .addComponent(etiquetaTotalDebe)
                                .addGap(18, 18, 18)
                                .addComponent(campoTotalDebe, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(etiquetaTotalHaber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoTotalHaber, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(etiquetaDiferencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoDiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRenglonesLayout.createSequentialGroup()
                                .addComponent(campoLeyenda, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonCancelar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRenglonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonVolverAlInicio)
                .addGap(34, 34, 34)
                .addComponent(botonGrabar)
                .addGap(66, 66, 66))
        );
        panelRenglonesLayout.setVerticalGroup(
            panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRenglonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNroRenglon)
                    .addComponent(etiquetaNroCuenta)
                    .addComponent(etiquetaFechaVencimiento)
                    .addComponent(etiquetaFechaOperacion)
                    .addComponent(etiquetaSucursal)
                    .addComponent(etiquetaSeccion))
                .addGap(9, 9, 9)
                .addGroup(panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoNroRenglon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoNroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRenglonesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(botonModificarRenglon)))
                .addGroup(panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRenglonesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRenglonesLayout.createSequentialGroup()
                                .addComponent(etiquetaComprobante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRenglonesLayout.createSequentialGroup()
                                .addGroup(panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(opcionDebe)
                                        .addComponent(etiquetaImporte))
                                    .addComponent(etiquetaNombreCuenta))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(opcionHaber)
                                    .addComponent(campoImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoNombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelRenglonesLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(botonEliminarRenglon)))
                .addGap(12, 12, 12)
                .addComponent(etiquetaLeyenda)
                .addGap(18, 18, 18)
                .addGroup(panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoLeyenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonOK)
                    .addComponent(botonCancelar))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaTotalDebe)
                    .addComponent(campoTotalDebe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaTotalHaber)
                    .addComponent(campoTotalHaber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaDiferencia)
                    .addComponent(campoDiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(panelRenglonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGrabar)
                    .addComponent(botonVolverAlInicio))
                .addContainerGap())
        );

        etiquetaIDAsiento.setText("ID:");

        etiquetaTipoAsiento.setText("Tipo de Asiento:");

        grupoTipoAsiento.add(opcionApertura);
        opcionApertura.setText("Apertura");

        grupoTipoAsiento.add(opcionNormal);
        opcionNormal.setText("Normal");

        grupoTipoAsiento.add(opcionCierre);
        opcionCierre.setText("Cierre");

        javax.swing.GroupLayout panelTipoAsientoLayout = new javax.swing.GroupLayout(panelTipoAsiento);
        panelTipoAsiento.setLayout(panelTipoAsientoLayout);
        panelTipoAsientoLayout.setHorizontalGroup(
            panelTipoAsientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoAsientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTipoAsientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcionCierre)
                    .addComponent(opcionNormal)
                    .addComponent(etiquetaTipoAsiento)
                    .addComponent(opcionApertura))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        panelTipoAsientoLayout.setVerticalGroup(
            panelTipoAsientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoAsientoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(etiquetaTipoAsiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opcionApertura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionCierre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGap(385, 385, 385)
                                .addComponent(etiquetaTitulo))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(etiquetaListar)
                                            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(botonListar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(panelPrincipalLayout.createSequentialGroup()
                                                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(etiquetaDesde)
                                                        .addComponent(etiquetaHasta))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(campoDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(campoHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(76, 76, 76))
                                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botonRetomarAsiento)
                                            .addComponent(botonNuevoAsiento)
                                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                                .addComponent(etiquetaIDAsiento)
                                                .addGap(18, 18, 18)
                                                .addComponent(campoRetomarAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(68, 68, 68)))
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelRenglones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                                        .addComponent(panelAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(panelTipoAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 135, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaTitulo)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(botonNuevoAsiento)
                        .addGap(52, 52, 52)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaIDAsiento)
                            .addComponent(campoRetomarAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonRetomarAsiento))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelTipoAsiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addComponent(etiquetaListar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaDesde)
                            .addComponent(campoDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaHasta)
                            .addComponent(campoHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(botonListar)
                        .addGap(350, 350, 350))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addComponent(panelRenglones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        botonSalir.setText("Salir");

        botonConfirmarAsiento.setText("Confirmar Asiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(botonConfirmarAsiento)
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSalir)
                    .addComponent(botonConfirmarAsiento))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAsientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonCancelar;
    public javax.swing.JButton botonConfirmarAsiento;
    public javax.swing.JButton botonEliminarRenglon;
    public javax.swing.JButton botonGrabar;
    public javax.swing.JButton botonIniciarCarga;
    public javax.swing.JButton botonListar;
    public javax.swing.JButton botonModificarRenglon;
    public javax.swing.JButton botonNuevoAsiento;
    public javax.swing.JButton botonOK;
    public javax.swing.JButton botonRetomarAsiento;
    public javax.swing.JButton botonSalir;
    public javax.swing.JButton botonVolverAlInicio;
    public javax.swing.JButton botonVolverAtras;
    public javax.swing.JTextField campoAsiento;
    public javax.swing.JTextField campoComprobante;
    public javax.swing.JTextField campoDesde;
    public javax.swing.JTextField campoDiferencia;
    public javax.swing.JTextField campoHasta;
    public javax.swing.JTextField campoImporte;
    public javax.swing.JTextField campoLeyenda;
    public static javax.swing.JTextField campoNombreCuenta;
    public static javax.swing.JTextField campoNroCuenta;
    public javax.swing.JTextField campoNroRenglon;
    public javax.swing.JTextField campoRetomarAsiento;
    public static javax.swing.JTextField campoSeccion;
    public static javax.swing.JTextField campoSucursal;
    public javax.swing.JTextField campoTotalDebe;
    public javax.swing.JTextField campoTotalHaber;
    public javax.swing.JCheckBox checkInflacion;
    public javax.swing.JLabel etiquetaComprobante;
    public javax.swing.JLabel etiquetaDesde;
    public javax.swing.JLabel etiquetaDiferencia;
    public javax.swing.JLabel etiquetaFechaContable;
    public javax.swing.JLabel etiquetaFechaOperacion;
    public javax.swing.JLabel etiquetaFechaVencimiento;
    public javax.swing.JLabel etiquetaHasta;
    public javax.swing.JLabel etiquetaIDAsiento;
    public javax.swing.JLabel etiquetaImporte;
    public javax.swing.JLabel etiquetaLeyenda;
    public javax.swing.JLabel etiquetaListar;
    public javax.swing.JLabel etiquetaNombreCuenta;
    public javax.swing.JLabel etiquetaNroAsiento;
    public javax.swing.JLabel etiquetaNroCuenta;
    public javax.swing.JLabel etiquetaNroRenglon;
    public javax.swing.JLabel etiquetaSeccion;
    public javax.swing.JLabel etiquetaSucursal;
    public javax.swing.JLabel etiquetaTipoAsiento;
    public javax.swing.JLabel etiquetaTitulo;
    public javax.swing.JLabel etiquetaTotalDebe;
    public javax.swing.JLabel etiquetaTotalHaber;
    public com.toedter.calendar.JDateChooser fechaContable;
    public com.toedter.calendar.JDateChooser fechaOperacion;
    public com.toedter.calendar.JDateChooser fechaVencimiento;
    public javax.swing.ButtonGroup grupoDebeHaber;
    public javax.swing.ButtonGroup grupoTipoAsiento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JRadioButton opcionApertura;
    public javax.swing.JRadioButton opcionCierre;
    public javax.swing.JRadioButton opcionDebe;
    public javax.swing.JRadioButton opcionHaber;
    public javax.swing.JRadioButton opcionNormal;
    public javax.swing.JPanel panelAsientos;
    public javax.swing.JPanel panelPrincipal;
    public javax.swing.JPanel panelRenglones;
    public javax.swing.JPanel panelTipoAsiento;
    public javax.swing.JTable tablaRenglones;
    // End of variables declaration//GEN-END:variables
}
